### ISSUE TITLE
Scanning path doesn't work with folder name contains space in Windows

### ISSUE THREAD

**Issue by bd-syu** [blackducksoftware/hub-jira#22]
No permission issue on the folder being scanned.

Started by user anonymous
Building in workspace C:\Program Files (x86)\Jenkins\jobs\BlackDuck test job\workspace
Getting Jdk on master :
JDK home : C:\Program Files (x86)\Jenkins\jre
Node workspace C:\Program Files (x86)\Jenkins\jobs\BlackDuck test job\workspace
Starting BlackDuck Scans...
Hub Plugin running on machine : SCAPC9
Problem getting the real path of the target : C:\Downloads\TFSFiles on this node. Error: The filename, directory name, or volume label syntax is incorrect
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
    at java.io.WinNTFileSystem.canonicalize0(Native Method)
    at java.io.WinNTFileSystem.canonicalize(Unknown Source)
    at java.io.File.getCanonicalPath(Unknown Source)
    at com.blackducksoftware.integration.hub.jenkins.remote.GetCanonicalPath.call(GetCanonicalPath.java:43)
    at com.blackducksoftware.integration.hub.jenkins.remote.GetCanonicalPath.call(GetCanonicalPath.java:32)
    at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
    at com.blackducksoftware.integration.hub.jenkins.scan.BDCommonScanStep.getScanTargets(BDCommonScanStep.java:382)
    at com.blackducksoftware.integration.hub.jenkins.scan.BDCommonScanStep.runScan(BDCommonScanStep.java:177)
    at com.blackducksoftware.integration.hub.jenkins.PostBuildHubScan.perform(PostBuildHubScan.java:167)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Initializing Hub
Jenkins Plugin 1.5.3
-> Running on : master
-> Log Level : INFO
-> Using Url : http://10.194.116.121:8080/
-> Using Username : sysadmin
-> Using Build Full Name : BlackDuck test job #13
-> Using Build Identifier : 13
-> Using Build Workspace Path : C:\Program Files (x86)\Jenkins\jobs\BlackDuck test job\workspace
-> Using Hub Project Name : PMUCE_CollationService, Version : 1.0-
-> Dry Run : false
-> Scanning the following targets :
-> C:\Downloads\TFSFiles
-> Generate Hub report : false
-> Maximum wait time for the BOM Update : 5 minutes
The selected Phase does not match the Phase of this Version. If you wish to update the Phase please do so in the Hub UI.
com.blackducksoftware.integration.hub.jenkins.exceptions.HubConfigurationException: Cannot scan targets outside of the workspace.
com.blackducksoftware.integration.hub.jenkins.exceptions.HubConfigurationException: Cannot scan targets outside of the workspace.
    at
com.blackducksoftware.integration.hub.jenkins.scan.BDCommonScanStep.validateScanTargets(BDCommonScanStep.java:699)
    at
com.blackducksoftware.integration.hub.jenkins.scan.BDCommonScanStep.runScan(BDCommonScanStep.java:516)
    at
com.blackducksoftware.integration.hub.jenkins.scan.BDCommonScanStep.runScan(BDCommonScanStep.java:272)
    at
com.blackducksoftware.integration.hub.jenkins.PostBuildHubScan.perform(PostBuildHubScan.java:167)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished running Black Duck Scans.
Build step 'Black Duck Hub Integration' changed build result to UNSTABLE
Finished: UNSTABLE

**Comment by stavvy-akamen** [comment]
@bd-syu Is this still an issue?

**Comment by jamesrichard91** [comment]
This does not appear to be an issue in the JIRA plugin. Please open an issue in the correct repository if this is still a problem
